package my.Login;
import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import my.Classes.*;
import static my.Classes.FileLocationInterface.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *   
 * @author dvdmi
 */
public class VendorOrderHistory extends javax.swing.JFrame {
    Vendor vendorAcc;
    private ArrayList<String> selectedOrder;
    /**
     * Creates new form VendorOrders
     */
    public VendorOrderHistory() {
        initComponents();
    }

    public VendorOrderHistory(Vendor vendorAccount) {
        initComponents();
        this.vendorAcc = vendorAccount;
        loadOrderHistory();
    }
    
    private void loadOrderHistory() {
        try {
            // Read order details from the Orders.txt file
            File ordersFile = new File(ordersFilePath);
            Scanner scanner = new Scanner(ordersFile);

            // Create the table model and set column names
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("OrderID");
            model.addColumn("Date");
            model.addColumn("Time");
            model.addColumn("Customer Name");

            while (scanner.hasNextLine()) {
                String orderData = scanner.nextLine();
                String[] orderDetails = orderData.split(",");

                // Check if the order status is "done"
                if (orderDetails.length >= 9 && orderDetails[5].equals("done")) {
                    // Fetch customer's full name from Users.txt based on CustomerID
                    String customerName = getCustomerFullName(orderDetails[3]);

                    // Add order details to the table model
                    model.addRow(new Object[]{orderDetails[0], orderDetails[1], orderDetails[2], customerName});
                }
            }

            scanner.close();

            // Set the model for the OrderHistoryTable
            OrderHistoryTable.setModel(model);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }

    private String getCustomerFullName(String customerID) {
        try {
            File usersFile = new File(userFilePath);
            Scanner scanner = new Scanner(usersFile);

            while (scanner.hasNextLine()) {
                String userData = scanner.nextLine();
                String[] userDetails = userData.split(",");

                if (userDetails.length >= 2 && userDetails[0].equals(customerID)) {
                    return userDetails[1]; // Full name
                }
            }
            scanner.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        return "Unknown";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrderHistoryTable = new javax.swing.JTable();
        BackButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OrderHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderID", "Date", "Time", "Customer Name"
            }
        ));
        jScrollPane1.setViewportView(OrderHistoryTable);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        VendorHomepage hp = new VendorHomepage(vendorAcc); // to go to the VendorMenu
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendorOrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendorOrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendorOrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendorOrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendorOrderHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BackButton;
    private javax.swing.JTable OrderHistoryTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
